# ref https://docs.docker.com/compose/compose-file/#build
services:
  # app:
  #   entrypoint:
  #   - sleep
  #   - infinity
  #   image: docker/dev-environments-default:stable-1
  #   init: true
  #   volumes:
  #   - type: bind
  #     source: /var/run/docker.sock
  #     target: /var/run/docker.sock

  app:
    build:
      context: .
      dockerfile: .\build\Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - .:/app
