version: '3'
services:
  glados:
    container_name: glados
    restart: unless-stopped
    # image: jkamsker/glados-tts:latest
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    ports:
      - "8124:8124"
    volumes:
      - ./output:/output # Persist output cache